services:
  - type: web
    name: lio-padel-league
    env: python
    # Deja buildCommand vacío para que Render use el pip por defecto
    buildCommand: ""
    startCommand: "gunicorn src.main:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: RENDER
        value: "true"
      - key: SECRET_KEY
        fromDatabase: true
      - key: DB_USER
        fromDatabase: true
      - key: DB_PASSWORD
        fromDatabase: true
      - key: DB_HOST
        fromDatabase: true
      - key: DB_PORT
        fromDatabase: true
      - key: DB_NAME
        fromDatabase: true
